[project]
name = "py-emagls"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scipy>=1.17.0",
    "sofar>=1.2.3",
    "soundfile>=0.13.1",
    "soxr>=1.0.0",
]
